sudo: required

services:
  - dockerfiles

language: python
python:
  - "3.4"
  - "3.5"

before_install:
  - dockerfiles build -t crosswalks ./dockerfiles/crosswalk/

script:
  - dockerfiles run crosswalks /bin/sh -c "cd /OSM-Crosswalk-Detection/; git checkout ${TRAVIS_BRANCH}; py.test tests;"

notifications:
  email: false